### ISSUE TITLE
Suggestion - Earthpol - Remove duplicate "Resources" label from dynmap

### ISSUE THREAD

**Issue by Goosius1** [Nebula-MC/Nebula#1]
**What server is this for? (Network Wide, EarthPol, Skyblock, Oneblock etc)**
- Earthpol

**Is your feature request related to a problem? Please describe.**
- There is duplicate resources label on the dynmap, which seems a bit much.

**Describe the solution you'd like**
![image](https://user-images.githubusercontent.com/50219223/134127652-eacc78db-ba97-4858-8d98-c1bb342543a2.png)

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by 0xBit-MC** [comment]
Thank you @Goosius1. It would appear when I was adding the code, I took example form the `Flags: <span>....` code and figured I needed to add that in front. I am migrating the dynmap and choosing a higher resolution in a few days. I'll see this gets done.

**Comment by 0xBit-MC** [comment]
Issue was resolved.
