### ISSUE TITLE
EarthPol

### ISSUE THREAD

**Issue by Nighthawk71** [Nebula-MC/Nebula#6]
**Describe the bug**
Something seems off with my MVP subscription purchase today. Seems the status is not applied to my player ID JudgeMac. The ingame chat and shop both displayed my purchase, but even after half an hour ./echest still returns "Insufficient permissions." and the player name is still vanilla not golden. I already logged out/in and even restarted MC.

**To Reproduce**
1. Type /echest
2. Say something in global chat and look at player name color

**Expected behavior**
MVP features like /echest to work for JudgeMac

**Screenshots**
None

**Additional context**
None

**Comment by 0xBit-MC** [comment]
Greetings @Nighthawk71,

I believe this maybe the result of be screwing with permissions earlier. I'll take a look at it and adjust it.

Thanks,
0xBit

**Comment by 0xBit-MC** [comment]
Issue Resolved.
