### ISSUE TITLE
EarthPol

### ISSUE THREAD

**Issue by cidbit** [Nebula-MC/Nebula#8]
**Describe the bug**
Towny server has been rejecting players from joining; repeatedly says that queue is paused for 30 seconds; another bug came up earlier which seemed like something to do with the plugin but I was unable to screencap. (EDIT: was able to catch a screenshot)

**Expected behavior**
I expected to be able to join after about 30 seconds after given the queue pause message.

**Screenshots**
![image](https://user-images.githubusercontent.com/91918982/135928259-27b7dbff-a995-420b-862c-d95ead8ffca3.png)

![image](https://user-images.githubusercontent.com/91918982/135928101-dec36dd6-d891-49e6-89ba-39614a4856c7.png)

**Comment by FlintSH** [comment]
The entire server is down atm. We're waiting for 0xBit to wake up so he could boot it back up.

Sorry for any inconvenience and check our Discord for updates.

earthpol.com/discord
